#pragma once

#include <SFML/Graphics.hpp>
#include <iostream>
#include <stdexcept>
#include <fstream>
#include <string>
#include <sstream>
#include <filesystem>
#include <string>
#include <ctime>
#include <iomanip>
#include "Drawio.h"
#include "Activity.h"
#include "LinkList.h"
#include "Teacher.h"
#include "Student.h"
#include "Components.h"
#include "ExtraFunction.h"
#include "User.h"
#include "FileNFolder.h"
