#pragma once
#include <SFML/Graphics.hpp>
#include <iostream>
#include <fstream>
#include <string>
#include "Drawio.h"
#include "Activity.h"
#include "LinkList.h"
#include "Teacher.h"
#include "Student.h"
#include "Components.h"